{
 "title": "Flink nexmark",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "task_name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured, task_name)"
    }
   },
   {
    "name": "subtask_index",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured, subtask_index)"
    }
   },
   {
    "name": "job_id",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured, job_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "True processing detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {},
    {
     "expr": "rate(flink_taskmanager_job_task_numRecordsIn{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}[30s]) * 1000/(avg_over_time(flink_taskmanager_job_task_busyTimeMsPerSecond{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}[30s:5s]))"
    }
   ]
  },
  {
   "title": "Total true processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_numRecordsIn{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}[30s]) * 1000/(avg_over_time(flink_taskmanager_job_task_busyTimeMsPerSecond{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}[30s:5s])))"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Busy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_busyTimeMsPerSecond{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}"
    },
    {
     "expr": "avg_over_time(flink_taskmanager_job_task_busyTimeMsPerSecond{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}[30s:5s])"
    }
   ]
  },
  {
   "title": "Busy (sum)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_busyTimeMsPerSecond{task_name=~\"$task_name\", job_id=~\"$job_id\"})"
    }
   ]
  },
  {
   "title": "BytesIn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesIn{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}"
    }
   ]
  },
  {
   "title": "BytesOut",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsOut{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}"
    }
   ]
  },
  {
   "title": "NumRecordsIn rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "irate(flink_taskmanager_job_task_numRecordsIn{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}[15s])"
    },
    {
     "expr": "rate(flink_taskmanager_job_task_numRecordsIn{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}[60s])"
    }
   ]
  },
  {
   "title": "NumRecordsOut rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "irate(flink_taskmanager_job_task_operator_numRecordsOut{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}[15s])"
    },
    {
     "expr": "rate(flink_taskmanager_job_task_operator_numRecordsOut{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}[60s])"
    }
   ]
  },
  {
   "title": "numRecordsIn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsIn{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}"
    }
   ]
  },
  {
   "title": "NumRecordsOut",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOut{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}"
    }
   ]
  },
  {
   "title": "Backpressure / second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_backPressuredTimeMsPerSecond{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Task usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_backPressuredTimeMsPerSecond{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}"
    },
    {
     "expr": "flink_taskmanager_job_task_idleTimeMsPerSecond{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}"
    },
    {
     "expr": "flink_taskmanager_job_task_busyTimeMsPerSecond{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{container=\"taskmanager\"}[30s])"
    }
   ]
  },
  {
   "title": "Pending records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_pendingRecords{})"
    }
   ]
  },
  { "title": "Throughput source/sink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Source events quantity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOut{task_name=~\"Source.*\", job_id=~\"$job_id\"})"
    }
   ]
  },
  {
   "title": "Sink events quantity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsIn{task_name=~\"Sink.*\", job_id=~\"$job_id\"})"
    }
   ]
  },
  {
   "title": "Sum records in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(irate(flink_taskmanager_job_task_numRecordsIn{task_name=~\"$task_name\", job_id=~\"$job_id\"}[15s]))"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_numRecordsIn{task_name=~\"$task_name\", job_id=~\"$job_id\"}[30s]))"
    }
   ]
  },
  {
   "title": "Sum records out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(irate(flink_taskmanager_job_task_numRecordsOut{task_name=~\"$task_name\", job_id=~\"$job_id\"}[15s]))"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_numRecordsOut{task_name=~\"$task_name\", job_id=~\"$job_id\"}[30s]))"
    }
   ]
  },
  {
   "title": "Throughput Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(irate(flink_taskmanager_job_task_operator_numRecordsOut{task_name=~\"Source.*\", job_id=~\"$job_id\"}[15s]))"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_numRecordsOut{task_name=~\"Source.*\", job_id=~\"$job_id\"}[30s]))"
    }
   ]
  },
  {
   "title": "Throughput Sink",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sum(irate(flink_taskmanager_job_task_operator_numRecordsIn{task_name=~\"Sink.*\", job_id=~\"$job_id\"}[15s]))"
    }
   ]
  },
  {
   "title": "Block Cache Hits (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"})",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "Block Cache Misses (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_rocksdb_block_cache_miss{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"})",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Block Cache Usage / Capacity / Pinned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max by (job_id, task_name, subtask_index) (flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_usage{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(max by (job_id, task_name, subtask_index) (flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_capacity{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}))",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(max by (job_id, task_name, subtask_index) (flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_pinned_usage{task_name=~\"$task_name\", subtask_index=~\"$subtask_index\", job_id=~\"$job_id\"}))",
     "legendFormat": "Pinned"
    }
   ]
  },
  { "title": "Garbage collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Copy_Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_GarbageCollector_Copy_Time"
    }
   ]
  },
  {
   "title": "MarkSweepCompact_Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Time"
    }
   ]
  },
  {
   "title": "PS_Scavenge_Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_GarbageCollector_PS_Scavenge_Time"
    }
   ]
  },
  {
   "title": "PS_MarkSweep_Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_GarbageCollector_PS_MarkSweep_Time"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Memory (container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"taskmanager\"} / (1000*1000*1000)"
    }
   ]
  },
  {
   "title": "Memory managed (in Go)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_Flink_Memory_Managed_Used"
    }
   ]
  },
  {
   "title": "Memory heap (in Go)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used / (1000*1000*1000)"
    }
   ]
  }
 ]
}