prometheus:
  service:
    type: NodePort
    nodePort: 30090
  prometheusSpec:
    nodeSelector:
      tier: jobmanager
    podMonitorSelectorNilUseHelmValues: false
grafana:
  service:
    type: NodePort
    nodePort: 30300
  nodeSelector:
    tier: jobmanager
kube-state-metrics:
  nodeSelector:
    tier: jobmanager
